import type { DimensionSet } from '@spaguettiscope/core';

export type TestStatus = 'passed' | 'failed' | 'skipped' | 'broken' | 'unknown';

export interface NormalizedRunRecord {
  /** UUID generated by the connector */
  id: string;
  /** Which connector produced this record */
  connectorId: string;
  /** ISO 8601 timestamp of when the test ran */
  runAt: string;
  /** Human-readable test name */
  name: string;
  /** Fully-qualified test name (suite + name, if available) */
  fullName: string;
  /** Test outcome */
  status: TestStatus;
  /** Duration in milliseconds */
  duration: number;
  /** Dimension values inferred or mapped from source data */
  dimensions: DimensionSet;
  /** Original source location */
  source: {
    /** Path to the result file read by the connector */
    file: string;
    connectorId: string;
  };
  /** Arbitrary extra data from the source format */
  metadata?: Record<string, unknown>;
}
